# GRIDWORLD

from [Intro to RL Textbook](https://www.andrew.cmu.edu/course/10-703/textbook/BartoSutton.pdf) Chapter 4, p.76

* S = {1, 2,..., 14}
* A = {up, down, right, left} at each state
* Each action **deterministically** cause the corresponding state transitions, EXCEPT actions that would take the agent out of the grid leave the state unchanged.
* undiscounted, episodic task
* **reward = -1** on all transitions until the terminal state is reached
* expected reward function = r(s, a, s') = -1 for all states s, s' and actions a. 
* terminal states: upper-leftmost cell & lower-rightmost cell


# 1 Policy Evaluation

(for Random policy, with equal probability of moving up, down, right, or left)

In [77]:
import numpy as np

In [82]:
# Initialize v, q & define r
v = np.zeros(16)
q = np.zeros((16,4))
r = np.ones(16)*-1
r[0] = r[-1] = 0

In [83]:
def next_i(i):
    i_up = i-4 if i>=4 else i
    i_down = i+4 if i<12 else i
    i_r = i+1 if (i+1)%4!=0 else i
    i_l = i-1 if i%4!=0 else i
    return i_up, i_down, i_r, i_l

In [84]:
# Policy Evaluation
max_iter = 10000
k = 0
cnt = 0
deltas = np.zeros(14)
while k<max_iter:
    prev_deltas = deltas.copy()
    
    for i in range(1,15,1):
        v_prev = v[i]
        i_up, i_down, i_r, i_l = next_i(i)
        v[i] = 0.25*(r[i_up] + v[i_up] +
                     r[i_down] + v[i_down] +
                     r[i_r] + v[i_r] +
                     r[i_l] + v[i_l]) # Up, Down, Right, Left       
        deltas[i-1] = max(deltas[i-1], abs(v_prev-v[i]))
    
    if deltas.all() == prev_deltas.all():
        cnt += 1 
        if cnt > 1000:
            break
    k+= 1

print("Value Function for Random Policy:")
print(np.array(v).reshape(4,4))    

Value Function for Random Policy:
[[  0. -13. -19. -21.]
 [-13. -17. -19. -19.]
 [-19. -19. -17. -13.]
 [-21. -19. -13.   0.]]


In [ ]:
for i in range(1,15,1):
    i_up, i_down, i_r, i_l = next_i(i)
    q[i] = [r[i] + v[i_up], r[i] + v[i_down], r[i] + v[i_r], r[i] + v[i_l]]

In [32]:
for i, state in enumerate(q):
    print(i, state)

0 [0. 0. 0. 0.]
1 [-14. -18. -20.  -1.]
2 [-20. -20. -22. -14.]
3 [-22. -20. -22. -20.]
4 [ -1. -20. -18. -14.]
5 [-14. -20. -20. -14.]
6 [-20. -18. -20. -18.]
7 [-22. -14. -20. -20.]
8 [-14. -22. -20. -20.]
9 [-18. -20. -18. -20.]
10 [-20. -14. -14. -20.]
11 [-20.  -1. -14. -18.]
12 [-20. -22. -20. -22.]
13 [-20. -20. -14. -22.]
14 [-18. -14.  -1. -20.]
15 [0. 0. 0. 0.]


# 2 Value Iteration

In [74]:
# Initialize v, q & define r
v = np.zeros(16)
q = np.zeros((16,4))
r = np.ones(16)*-1
r[0] = r[-1] = 0

In [75]:
# I. Policy Evaluation
max_iter = 10000
k = 0
cnt = 0
deltas = np.zeros(14)
while k<max_iter:
    prev_deltas = deltas.copy()
    
    for i in range(1,15,1):
        v_prev = v[i]
        i_up, i_down, i_r, i_l = next_i(i)
        v[i] = max(r[i_up] + v[i_up], 
                   r[i_down] + v[i_down], 
                   r[i_r] + v[i_r], 
                   r[i_l] + v[i_l]) # Up, Down, Right, Left     
        deltas[i-1] = max(deltas[i-1], abs(v_prev-v[i]))
    
    if deltas.all() == prev_deltas.all():
        cnt += 1 
        if cnt > 1000:
            break   
    k+= 1

print("Opitmal Value Function:")
print(np.array(v).reshape(4,4))  

# II. Policy Update
policy = np.zeros(16)
for i in range(1,15,1):
    i_up, i_down, i_r, i_l = next_i(i)
    policy[i] = np.argmax([r[i_up] + v[i_up], 
                           r[i_down] + v[i_down], 
                           r[i_r] + v[i_r], 
                           r[i_l] + v[i_l]])

print("\n\nOptimal Policy:\n(0 = Up, 1 = Down, 2 = Right, 3 = Left)")
print(policy.reshape(4,4))

Opitmal Value Function:
[[ 0.  0. -1. -2.]
 [ 0. -1. -2. -1.]
 [-1. -2. -1.  0.]
 [-2. -1.  0.  0.]]


Optimal Policy:
(0 = Up, 1 = Down, 2 = Right, 3 = Left)
[[0. 3. 3. 1.]
 [0. 0. 0. 1.]
 [0. 0. 1. 1.]
 [0. 2. 2. 0.]]
