In [3]:
import numpy as np
from tabulate import tabulate

In [29]:
v = np.zeros(16)
q = np.zeros((16,4))
r = np.ones(16)*-1
r[0] = r[-1] = 0
threshold = 0.01
delta = 0

In [30]:
max_iter = 10000
k = 0
while k<max_iter and (delta > threshold or delta == 0):
    for i in range(1,15,1):
        v_prev = v[i]
        i_up = i-4 if i>=4 else i
        i_down = i+4 if i<12 else i
        i_r = i+1 if (i+1)%4!=0 else i
        i_l = i-1 if i%4!=0 else i
        v[i] = 0.25*(r[i_up]+v[i_up] + r[i_down]+v[i_down] + r[i_r] + v[i_r] + r[i_l] + v[i_l]) # Up, Down, Right, Left
        
        delta = max(delta, abs(v_prev-v[i]))

    if k%1000 == 0:
        print(k)
        print(delta)
        print(np.array(v).reshape(4,4))    
    k+= 1

0
1.8203125
[[ 0.         -0.75       -1.1875     -1.296875  ]
 [-0.75       -1.375      -1.640625   -1.734375  ]
 [-1.1875     -1.640625   -1.8203125  -1.63867188]
 [-1.296875   -1.734375   -1.63867188  0.        ]]
1000
1.8203125
[[  0. -13. -19. -21.]
 [-13. -17. -19. -19.]
 [-19. -19. -17. -13.]
 [-21. -19. -13.   0.]]
2000
1.8203125
[[  0. -13. -19. -21.]
 [-13. -17. -19. -19.]
 [-19. -19. -17. -13.]
 [-21. -19. -13.   0.]]
3000
1.8203125
[[  0. -13. -19. -21.]
 [-13. -17. -19. -19.]
 [-19. -19. -17. -13.]
 [-21. -19. -13.   0.]]
4000
1.8203125
[[  0. -13. -19. -21.]
 [-13. -17. -19. -19.]
 [-19. -19. -17. -13.]
 [-21. -19. -13.   0.]]
5000
1.8203125
[[  0. -13. -19. -21.]
 [-13. -17. -19. -19.]
 [-19. -19. -17. -13.]
 [-21. -19. -13.   0.]]
6000
1.8203125
[[  0. -13. -19. -21.]
 [-13. -17. -19. -19.]
 [-19. -19. -17. -13.]
 [-21. -19. -13.   0.]]
7000
1.8203125
[[  0. -13. -19. -21.]
 [-13. -17. -19. -19.]
 [-19. -19. -17. -13.]
 [-21. -19. -13.   0.]]
8000
1.8203125
[[  0. -13. 

In [ ]:
for i in range(1,15,1):
    i_up = i-4 if i>=4 else i
    i_down = i+4 if i<12 else i
    i_r = i+1 if (i+1)%4!=0 else i
    i_l = i-1 if i%4!=0 else i
    q[i] = [r[i] + v[i_up], r[i] + v[i_down], r[i] + v[i_r], r[i] + v[i_l]]

In [32]:
for i, state in enumerate(q):
    print(i, state)

0 [0. 0. 0. 0.]
1 [-14. -18. -20.  -1.]
2 [-20. -20. -22. -14.]
3 [-22. -20. -22. -20.]
4 [ -1. -20. -18. -14.]
5 [-14. -20. -20. -14.]
6 [-20. -18. -20. -18.]
7 [-22. -14. -20. -20.]
8 [-14. -22. -20. -20.]
9 [-18. -20. -18. -20.]
10 [-20. -14. -14. -20.]
11 [-20.  -1. -14. -18.]
12 [-20. -22. -20. -22.]
13 [-20. -20. -14. -22.]
14 [-18. -14.  -1. -20.]
15 [0. 0. 0. 0.]
